# This file is for the labeler workflow
# Documentation https://github.com/marketplace/actions/labeler

Documentation:
  - changed-files:
      - any-glob-to-any-file: [www/**, "./*.{md,mdx}"]

"Type: Test":
  - changed-files:
      - any-glob-to-any-file: [tests/**, "*_test*"]

"Type: CI":
  - changed-files:
      - any-glob-to-any-file: [.github/workflows/**]
