name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: "Test on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: echo "temporary"

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
